"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: unitree_go.msg.dds_
  IDL file: BmsState_.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
# import unitree_go


@dataclass
@annotate.final
@annotate.autoid("sequential")
class BmsState_(idl.IdlStruct, typename="unitree_go.msg.dds_.BmsState_"):
    version_high: types.uint8 #组成电池版本信息
    version_low: types.uint8 #组成电池版本信息
    status: types.uint8 #显示未开启电池、唤醒事件、电池预充电中、电池正常充电中、电池正常放电中、电池自放电中、电池存在警告、等待按键复位警告中、复位中这些状态。
#     0：SAFE,（未开启电池） 1：WAKE_UP,（唤醒事件） 6：PRECHG, （电池预冲电中） 7：CHG, （电池正常充电中）
# // 8：DCHG, （电池正常放电中）9：SELF_DCHG, （电池自放电中） 11：ALARM, （电池存在警告） 12：RESET_ALARM, （等待按键复位警告中）13：AUTO_RECOVERY （复位中）
    soc: types.uint8 #电池电量信息（1% - 100%）。
    current: types.int32  #充放电信息：（正：代表充电，负代表放电）可按照实际数值显示
    cycle: types.uint16 # //充电循环次数
    bq_ntc: types.array[types.uint8, 2] #电池内部两个NTC的温度（int8_t）（范围：-100 - 150）。  0- BAT1; 1- BAT2
    mcu_ntc: types.array[types.uint8, 2]  #电池NTC数组：0 - RES，1 - MOS （int8_t）（范围：-100 - 150）。
    cell_vol: types.array[types.uint16, 15] #//电池内部15节电池的电压。


