"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: unitree_go.msg.dds_
  IDL file: IMUState_.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
# import unitree_go


@dataclass
@annotate.final
@annotate.autoid("sequential")
class IMUState_(idl.IdlStruct, typename="unitree_go.msg.dds_.IMUState_"):
    quaternion: types.array[types.float32, 4] #提供机身姿态信息之实时的 四元数信息。（0-w, 1-x, 2-y, 3-z）。
    gyroscope: types.array[types.float32, 3] #  提供机身机身姿态信息之实时的 三角速度信息。（0-x, 1-y, 2-z）。
    accelerometer: types.array[types.float32, 3] # 提供机身机身姿态信息之实时的 三轴加速度信息。（0-x, 1-y, 2-z）。
    rpy: types.array[types.float32, 3] #  提供机身机身姿态信息之实时的 欧拉角信息。（0-roll，1-pitch，2-yaw ）。
    temperature: types.uint8 #提供IMU温度信息（摄氏度）


